import type { Metadata } from "next";
import { ThemeProvider } from './providers/ThemeProvider';
import StyledComponentsRegistry from './registry';
import { Header } from "@/components/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru'>
      <body>
        <StyledComponentsRegistry>
          <ThemeProvider>
            <Header />
            {children}
            </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
